[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Monitor Serial
monitor_speed = 115200

upload_speed = 921600

; Dependencias de librerías
lib_deps =
    fastled/FastLED
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    https://github.com/jvpernis/esp32-ps3