[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Monitor Serial
monitor_speed = 115200

; Velocidad de carga (Útil si tienes errores al subir el código)
upload_speed = 921600

; Dependencias de librerías
lib_deps =
	FastLED
	git+https://github.com/jvpernis/esp32-ps3.git#1.1.0

; Para activar PS3 Bluetooth, habilita la siguiente línea:
build_flags = -D USE_PS3
